src/blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from blog import views

from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

app_name = 'blog'

urlpatterns = [
    path('', cache_page(CACHE_TTL)(views.BlogIndexView.as_view()), name='index'),
    path('<category>/', cache_page(CACHE_TTL)(views.PostByCategoryListView.as_view()), name='category'),
    path('<category>/<slug:slug>', cache_page(CACHE_TTL)(views.PostDetailView.as_view()), name='detail'),
]

src/gregcsokas/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django_otp.admin import OTPAdminSite

from core import views as core_views

admin.site.__class__ = OTPAdminSite

urlpatterns = [
    path('', core_views.SinglePageView.as_view(), name='index'),
    path('about/', core_views.SinglePageView.as_view(), name='about'),
    path('gc-admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('lab/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/blog/models.py
from django.db import models
from model_utils import Choices
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from martor.models import MartorField


class Category(models.Model):
    """ Category model."""

    name = models.CharField(_('category name'), max_length=50)
    slug = models.SlugField(_('category slug'), max_length=50, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)


class Tag(models.Model):
    """Tag model."""

    name = models.CharField(_('tag'), max_length=25, blank=True)

    class Meta:
        ordering = ['-name']

    def __str__(self):
        return self.name


class TimeStampModel(models.Model):
    """ Time stamp abstract model."""

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ContentModel(TimeStampModel):
    """ Content abstract model."""

    content = MartorField(_('content'))

    class Meta:
        abstract = True


class Post(ContentModel):
    """Post model."""

    STATUSES = Choices(
        (0, 'draft', _('draft')),
        (1, 'published', _('published')),
        (2, 'private', _('private')),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_staff': True},
                               null=True, related_name='blog_posts')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag')
    title = models.CharField(_('post title'), max_length=100)
    slug = models.SlugField(_('post slug'), max_length=105, blank=True, unique=True)
    head_image = models.ImageField(upload_to='uploads/', default='no-image')
    status = models.IntegerField(choices=STATUSES, default=STATUSES.draft, db_index=True)
    pub_date = models.DateTimeField(_('publication date'), default=timezone.now)
    comments = models.BooleanField(_('allow comments'), default=True)
    view_count = models.IntegerField(_('sum of views'), default=0)
    favs = models.IntegerField(_('sum of favourites'), default=0)

    class Meta:
        unique_together = ('slug', 'created')
        ordering = ['-pub_date']

    objects = models.Manager()

    @property
    def is_public(self):
        if self.status is Post.STATUSES.published and not self.pub_date > timezone.now():
            return True
        else:
            return False

    def get_absolute_url(self):
        return "{}/{}".format(self.category.slug, self.slug)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

src/core/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.postgres.fields import ArrayField

from martor.models import MartorField


class FilterUrl(models.Model):
    """ Filter URL abstract model."""

    filter_url = models.CharField(_("text type url field for metadata"), max_length=100,
                                  unique=True, blank=True, null=True)

    class Meta:
        abstract = True


class MetaData(FilterUrl):
    """ Metadata model. It contains page specific metadata filtered by url"""

    title = models.CharField(_("page title"), max_length=60)
    viewport = models.CharField(_("viewport"), max_length=100,
                                default="width=device-width, initial-scale=1")

    description = models.CharField(_("page description"), max_length=165)
    keywords = ArrayField(models.CharField(max_length=10, blank=True), default=list)
    author = models.ForeignKey(User, on_delete=models.SET_NULL,
                               null=True, limit_choices_to={'is_staff': True})

    class Meta:
        pass

    def __str__(self):
        return self.title


class SinglePage(FilterUrl):
    """Single page model."""

    title = models.CharField(_("page title"), max_length=60)
    content = MartorField(_("page content"))

    class Meta:
        pass

    def __str__(self):
        return self.title

src/blog/views.py
# -*- coding: utf-8 -*-
import logging
from django.views import generic

from blog.models import Post


logger = logging.getLogger('gregcsokas' + __name__)


class BlogIndexView(generic.ListView):
    """
    Blog index view which is return with all blog posts.
    Except draft or private posts if the user is not in staff group
    """

    template_name = 'post_list.html'
    model = Post
    context_object_name = 'posts'
    queryset = Post.objects.select_related('category').select_related('author').prefetch_related('tags').distinct()

    def get_queryset(self):

        posts = [post for post in self.queryset.iterator() if post.is_public or self.request.user.is_staff]

        return posts

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        context['categories'] = set(post.category for post in self.get_queryset())

        return context


class PostByCategoryListView(generic.ListView):
    """
    Post list view which is return with category specific post.
    Except draft or private posts if the user is not in staff group
    """

    template_name = 'post_list.html'
    model = Post
    context_object_name = 'posts'
    queryset = Post.objects.select_related('category').select_related('author').prefetch_related('tags').distinct()

    def get_queryset(self, **kwargs):
        queryset = self.queryset.filter(category__slug=self.kwargs['category'])

        posts = [post for post in queryset.iterator() if post.is_public or self.request.user.is_staff]

        return posts

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        context['categories'] = set(post.category for post in BlogIndexView.get_queryset(self))

        return context


class PostDetailView(generic.DetailView):
    """ """

    template_name = 'post_detail.html'
    model = Post
    queryset = Post.objects.all()

    def get_object(self):
        obj = super().get_object()

        return obj

src/core/views.py
# -*- coding: utf-8 -*-
from django.views import generic
from django.shortcuts import get_object_or_404

from core.models import SinglePage


class SinglePageView(generic.TemplateView):
    template_name = "simple_view.html"

    def get_context_data(self, **kwargs):
        context = super(SinglePageView, self).get_context_data(**kwargs)
        context["content"] = get_object_or_404(SinglePage, filter_url=self.request.path)

        return context

src/blog/templates/post_detail.html
{% extends 'base/base.html' %}
{% load martortags %}

{% block content %}
<section>
  <h3>{{ object.title }}</h3>
    <article>
      <header>
      </header>

      <div class="post-content-wo-img">
        {% if post.head_image != "no-img" %}
          <img class="head-image" src="{{ MEDIA_URL }}{{ post.head_image }}">
        {% endif %}

        <div>
          {{ post.content|safe_markdown }}
        </div>
      </div>
    </article>
  </section>
{% endblock %}

src/blog/templates/post_list.html
{% extends 'base/base.html' %}
{% load martortags %}

{% block content %}

  <section>
    <h3>post::list</h3>

      {% for post in posts %}
        <article class="container row-no-wrap">

          <header class="post-image ju-s">
            <div class="title-matrice">
              <div class="side-color"></div>
              <h4 class="by">{{ post.title }}</h4>
              <span class="by">by {{ post.author }}</span>
            </div>
          </header>

          <div class="post-content">
            <span>{{ post.content|safe_markdown|truncatewords:100 }}</span>
            <div class="container post-link ju-e"><a  href="{% url 'blog:index' %}{{ post.get_absolute_url }}">Tovább ...</a></div>
          </div>
        </article>
      {% endfor %}

  </section>
{% endblock %}

src/core/templates/simple_view.html
{% extends 'base/base.html' %}
{% load martortags %}

{% block content %}
  <section>
    <h3>{{ content.title }}</h3>
    {{ content.content|safe_markdown }}
  </section>
{% endblock %}

src/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  {% include 'base/head.html' %}

</head>
<body class="col">

  {% include 'base/header.html' %}

  {% block content %}

  {% endblock %}

  {% include 'base/footer.html' %}

</body>
<script async src="https://pro.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-I3Hhe9TkmlsxzooTtbRzdeLbmkFQE9DVzX/19uTZfHk1zn/uWUyk+a+GyrHyseSq" crossorigin="anonymous"></script>
</html>

src/templates/base/footer.html
<footer class="container col-no-wrap">
  <div class="container row-no-wrap">
    {% for com in common %}
      <div>
        <h4>{{ com }}</h4>
        <p>{{ com.content|safe }}</p>
      </div>
    {% endfor %}
    </div>
    <div class="copyright-box">
        <hr />
            <span class="copyright-text">
                <i class="fal fa-copyright fa-xs" data-fa-transform="up-10"></i> Greg Csokas {% now "Y" %}
            </span>
    </div>
</footer>

src/templates/base/head.html
{% load static %}

<meta content="text/html" charset="UTF-8" />
<meta name="viewport" content="{{ meta.viewport }}">
<title>{{ meta.title }}</title>
<meta name="description" content="{{ meta.description }}" />
<meta name="keywords" content="{{ meta.keywords }}" />
<meta name="author" content="{{ meta.author }}" />

<link rel="stylesheet" type="text/css" href="{% static "css/golden-compass.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/colors.css" %}" />
{#<link rel="stylesheet" type="text/css" href="{% static "css/mediaquery.css" %}" />#}

<script async src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>
  $( document ).ready(function() {
    $(".side-color").each(function () {
        var x = Math.floor(Math.random() * 256);
        var y = Math.floor(Math.random() * 256);
        var z = Math.floor(Math.random() * 256);
        var bgColor = "rgb(" + x + "," + y + "," + z + ")";
        $(this).css("background-color", bgColor);
    });
  });
</script>

src/templates/base/header.html
{% load i18n %}

  <nav class="container row-no-wrap">
    <ul class="menu container ju-c">
      <li class="menu-item"> <a class="home" href="/">Greg Csokas</a></li>
      <li class="menu-item"> <a href="/about/">Bio</a> </li>
      <li class="menu-item"> <a href="/cv/" disabled>CV</a> </li>
      <li class="menu-item"> <a href="/portfolio/" disabled>Portfolio</a> </li>
      <li class="menu-item"> <a href="/lab/">Lab</a>
        <ul class="container col-no-wrap sub-menu">
          {% if not categories %}
            <li class="">{% trans "no categories"|capfirst %}</li>
          {% else %}
            {% for category in categories %}
              <li class="sub-menu-item"> <a href="{% url 'blog:index' %}{{ category.slug }}/">{{ category.name }}</a> </li>
            {% endfor %}
          {% endif %}
        </ul>
      </li>
{#      <li class="menu-item search">#}
{#        <form class="container row-no-wrap" role="search" method="get" action="">#}
{#          <input class="search_text" type="text" name="search" id="search" placeholder="Search"/>#}
{#          <button class="search-button" type="submit"><i class="fal fa-search"></i></button>#}
{#        </form>#}
{#      </li>#}
{#      <li class="menu-item login">#}
{#        {% if user.is_authenticated %}#}
{#          <a href="/settings/"><i class="fal fa-sliders-h"></i></a>#}
{#        {% else %}#}
{#          <a href="/login/"><i class="fal fa-sign-in-alt"></i></a>#}
{#        {% endif %}#}
{#      </li>#}
{#      {% if user.is_authenticated %}#}
{#        <li class="menu-item login">#}
{#          <a href="/logout/"><i class="fal fa-sign-out-alt"></i></a>#}
{#        </li>#}
{#      {% endif %}#}
    </ul>
  </nav>